# Generated by Django 4.1.7 on 2023-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('St_id', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Experience', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Salary', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_staff',
            },
        ),
        migrations.CreateModel(
            name='tbl_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Student_class', models.CharField(max_length=30)),
                ('Marks', models.IntegerField()),
                ('Status', models.CharField(max_length=30)),
                ('Parent_Name', models.CharField(max_length=30)),
                ('Contact_Number', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_students',
            },
        ),
        migrations.CreateModel(
            name='tbl_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_id', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Joining_Date', models.DateField()),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=30)),
                ('Salary', models.IntegerField()),
                ('Subject', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_teacher',
            },
        ),
    ]
