# Generated by Django 4.1.7 on 2023-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_staff',
            name='St_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_students',
            name='S_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_students',
            name='Student_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_teacher',
            name='T_id',
            field=models.IntegerField(),
        ),
    ]
