# Generated by Django 4.1.7 on 2023-04-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appschool", "0002_alter_tbl_staff_st_id_alter_tbl_students_s_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tbl_teacher",
            name="Joining_Date",
        ),
    ]
